refactor: improves error message

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,9 +1,9 @@
 echo 'Check for linting errors...'
 npm run check || 
-(echo 'Linting errors or tests failed. Please fix them before commiting.' && exit 1)
+(echo 'Prettier errors failed. Please fix them before commiting.' && exit 1)
 
 npm run lint || 
-(echo 'Linting errors or tests failed. Please fix them before commiting.' && exit 1)
+(echo 'Linting errors failed. Please fix them before commiting.' && exit 1)
 
 
 echo 'Done'
